/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertiesIndexRouteImport } from './routes/properties.index'
import { Route as PropertyPropertyIdRouteImport } from './routes/property.$propertyId'
import { Route as PropertiesCreateRouteImport } from './routes/properties.create'
import { Route as AuthTableRouteImport } from './routes/_auth.table'
import { Route as AuthSavedRouteImport } from './routes/_auth.saved'
import { Route as AuthMyAccountRouteImport } from './routes/_auth.my-account'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyPropertyIdRoute = PropertyPropertyIdRouteImport.update({
  id: '/property/$propertyId',
  path: '/property/$propertyId',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesCreateRoute = PropertiesCreateRouteImport.update({
  id: '/properties/create',
  path: '/properties/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTableRoute = AuthTableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSavedRoute = AuthSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMyAccountRoute = AuthMyAccountRouteImport.update({
  id: '/my-account',
  path: '/my-account',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/my-account': typeof AuthMyAccountRoute
  '/saved': typeof AuthSavedRoute
  '/table': typeof AuthTableRoute
  '/properties/create': typeof PropertiesCreateRoute
  '/property/$propertyId': typeof PropertyPropertyIdRoute
  '/properties': typeof PropertiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/my-account': typeof AuthMyAccountRoute
  '/saved': typeof AuthSavedRoute
  '/table': typeof AuthTableRoute
  '/properties/create': typeof PropertiesCreateRoute
  '/property/$propertyId': typeof PropertyPropertyIdRoute
  '/properties': typeof PropertiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_auth/my-account': typeof AuthMyAccountRoute
  '/_auth/saved': typeof AuthSavedRoute
  '/_auth/table': typeof AuthTableRoute
  '/properties/create': typeof PropertiesCreateRoute
  '/property/$propertyId': typeof PropertyPropertyIdRoute
  '/properties/': typeof PropertiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/my-account'
    | '/saved'
    | '/table'
    | '/properties/create'
    | '/property/$propertyId'
    | '/properties'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/my-account'
    | '/saved'
    | '/table'
    | '/properties/create'
    | '/property/$propertyId'
    | '/properties'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/register'
    | '/_auth/my-account'
    | '/_auth/saved'
    | '/_auth/table'
    | '/properties/create'
    | '/property/$propertyId'
    | '/properties/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  PropertiesCreateRoute: typeof PropertiesCreateRoute
  PropertyPropertyIdRoute: typeof PropertyPropertyIdRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/': {
      id: '/properties/'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/$propertyId': {
      id: '/property/$propertyId'
      path: '/property/$propertyId'
      fullPath: '/property/$propertyId'
      preLoaderRoute: typeof PropertyPropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/create': {
      id: '/properties/create'
      path: '/properties/create'
      fullPath: '/properties/create'
      preLoaderRoute: typeof PropertiesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/table': {
      id: '/_auth/table'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof AuthTableRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/saved': {
      id: '/_auth/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AuthSavedRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/my-account': {
      id: '/_auth/my-account'
      path: '/my-account'
      fullPath: '/my-account'
      preLoaderRoute: typeof AuthMyAccountRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthMyAccountRoute: typeof AuthMyAccountRoute
  AuthSavedRoute: typeof AuthSavedRoute
  AuthTableRoute: typeof AuthTableRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthMyAccountRoute: AuthMyAccountRoute,
  AuthSavedRoute: AuthSavedRoute,
  AuthTableRoute: AuthTableRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  PropertiesCreateRoute: PropertiesCreateRoute,
  PropertyPropertyIdRoute: PropertyPropertyIdRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
