/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertiesIndexRouteImport } from './routes/properties.index'
import { Route as PropertyPropertyIdRouteImport } from './routes/property.$propertyId'
import { Route as PropertiesCreateRouteImport } from './routes/properties.create'
import { Route as AuthMyAccountRouteImport } from './routes/_auth.my-account'
import { Route as AuthDashboardRouteRouteImport } from './routes/_auth/dashboard.route'
import { Route as AuthDashboardIndexRouteImport } from './routes/_auth/dashboard.index'
import { Route as AuthDashboardSettingsRouteImport } from './routes/_auth/dashboard.settings'
import { Route as AuthDashboardExpensiveRouteImport } from './routes/_auth/dashboard.expensive'
import { Route as AuthDashboardMessagesRouteRouteImport } from './routes/_auth/dashboard.messages.route'
import { Route as AuthDashboardInvoicesRouteRouteImport } from './routes/_auth/dashboard.invoices.route'
import { Route as AuthDashboardMessagesIndexRouteImport } from './routes/_auth/dashboard.messages.index'
import { Route as AuthDashboardInvoicesIndexRouteImport } from './routes/_auth/dashboard.invoices.index'
import { Route as AuthDashboardInvoicesInvoiceIdRouteImport } from './routes/_auth/dashboard.invoices.$invoiceId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyPropertyIdRoute = PropertyPropertyIdRouteImport.update({
  id: '/property/$propertyId',
  path: '/property/$propertyId',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesCreateRoute = PropertiesCreateRouteImport.update({
  id: '/properties/create',
  path: '/properties/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMyAccountRoute = AuthMyAccountRouteImport.update({
  id: '/my-account',
  path: '/my-account',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRouteRoute = AuthDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardIndexRoute = AuthDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthDashboardRouteRoute,
} as any)
const AuthDashboardSettingsRoute = AuthDashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthDashboardRouteRoute,
} as any)
const AuthDashboardExpensiveRoute = AuthDashboardExpensiveRouteImport.update({
  id: '/expensive',
  path: '/expensive',
  getParentRoute: () => AuthDashboardRouteRoute,
} as any)
const AuthDashboardMessagesRouteRoute =
  AuthDashboardMessagesRouteRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthDashboardRouteRoute,
  } as any)
const AuthDashboardInvoicesRouteRoute =
  AuthDashboardInvoicesRouteRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthDashboardRouteRoute,
  } as any)
const AuthDashboardMessagesIndexRoute =
  AuthDashboardMessagesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthDashboardMessagesRouteRoute,
  } as any)
const AuthDashboardInvoicesIndexRoute =
  AuthDashboardInvoicesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthDashboardInvoicesRouteRoute,
  } as any)
const AuthDashboardInvoicesInvoiceIdRoute =
  AuthDashboardInvoicesInvoiceIdRouteImport.update({
    id: '/$invoiceId',
    path: '/$invoiceId',
    getParentRoute: () => AuthDashboardInvoicesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthDashboardRouteRouteWithChildren
  '/my-account': typeof AuthMyAccountRoute
  '/properties/create': typeof PropertiesCreateRoute
  '/property/$propertyId': typeof PropertyPropertyIdRoute
  '/properties': typeof PropertiesIndexRoute
  '/dashboard/invoices': typeof AuthDashboardInvoicesRouteRouteWithChildren
  '/dashboard/messages': typeof AuthDashboardMessagesRouteRouteWithChildren
  '/dashboard/expensive': typeof AuthDashboardExpensiveRoute
  '/dashboard/settings': typeof AuthDashboardSettingsRoute
  '/dashboard/': typeof AuthDashboardIndexRoute
  '/dashboard/invoices/$invoiceId': typeof AuthDashboardInvoicesInvoiceIdRoute
  '/dashboard/invoices/': typeof AuthDashboardInvoicesIndexRoute
  '/dashboard/messages/': typeof AuthDashboardMessagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/my-account': typeof AuthMyAccountRoute
  '/properties/create': typeof PropertiesCreateRoute
  '/property/$propertyId': typeof PropertyPropertyIdRoute
  '/properties': typeof PropertiesIndexRoute
  '/dashboard/expensive': typeof AuthDashboardExpensiveRoute
  '/dashboard/settings': typeof AuthDashboardSettingsRoute
  '/dashboard': typeof AuthDashboardIndexRoute
  '/dashboard/invoices/$invoiceId': typeof AuthDashboardInvoicesInvoiceIdRoute
  '/dashboard/invoices': typeof AuthDashboardInvoicesIndexRoute
  '/dashboard/messages': typeof AuthDashboardMessagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_auth/dashboard': typeof AuthDashboardRouteRouteWithChildren
  '/_auth/my-account': typeof AuthMyAccountRoute
  '/properties/create': typeof PropertiesCreateRoute
  '/property/$propertyId': typeof PropertyPropertyIdRoute
  '/properties/': typeof PropertiesIndexRoute
  '/_auth/dashboard/invoices': typeof AuthDashboardInvoicesRouteRouteWithChildren
  '/_auth/dashboard/messages': typeof AuthDashboardMessagesRouteRouteWithChildren
  '/_auth/dashboard/expensive': typeof AuthDashboardExpensiveRoute
  '/_auth/dashboard/settings': typeof AuthDashboardSettingsRoute
  '/_auth/dashboard/': typeof AuthDashboardIndexRoute
  '/_auth/dashboard/invoices/$invoiceId': typeof AuthDashboardInvoicesInvoiceIdRoute
  '/_auth/dashboard/invoices/': typeof AuthDashboardInvoicesIndexRoute
  '/_auth/dashboard/messages/': typeof AuthDashboardMessagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/my-account'
    | '/properties/create'
    | '/property/$propertyId'
    | '/properties'
    | '/dashboard/invoices'
    | '/dashboard/messages'
    | '/dashboard/expensive'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/invoices/$invoiceId'
    | '/dashboard/invoices/'
    | '/dashboard/messages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/my-account'
    | '/properties/create'
    | '/property/$propertyId'
    | '/properties'
    | '/dashboard/expensive'
    | '/dashboard/settings'
    | '/dashboard'
    | '/dashboard/invoices/$invoiceId'
    | '/dashboard/invoices'
    | '/dashboard/messages'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/register'
    | '/_auth/dashboard'
    | '/_auth/my-account'
    | '/properties/create'
    | '/property/$propertyId'
    | '/properties/'
    | '/_auth/dashboard/invoices'
    | '/_auth/dashboard/messages'
    | '/_auth/dashboard/expensive'
    | '/_auth/dashboard/settings'
    | '/_auth/dashboard/'
    | '/_auth/dashboard/invoices/$invoiceId'
    | '/_auth/dashboard/invoices/'
    | '/_auth/dashboard/messages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  PropertiesCreateRoute: typeof PropertiesCreateRoute
  PropertyPropertyIdRoute: typeof PropertyPropertyIdRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/': {
      id: '/properties/'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/$propertyId': {
      id: '/property/$propertyId'
      path: '/property/$propertyId'
      fullPath: '/property/$propertyId'
      preLoaderRoute: typeof PropertyPropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/create': {
      id: '/properties/create'
      path: '/properties/create'
      fullPath: '/properties/create'
      preLoaderRoute: typeof PropertiesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/my-account': {
      id: '/_auth/my-account'
      path: '/my-account'
      fullPath: '/my-account'
      preLoaderRoute: typeof AuthMyAccountRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard/': {
      id: '/_auth/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthDashboardIndexRouteImport
      parentRoute: typeof AuthDashboardRouteRoute
    }
    '/_auth/dashboard/settings': {
      id: '/_auth/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthDashboardSettingsRouteImport
      parentRoute: typeof AuthDashboardRouteRoute
    }
    '/_auth/dashboard/expensive': {
      id: '/_auth/dashboard/expensive'
      path: '/expensive'
      fullPath: '/dashboard/expensive'
      preLoaderRoute: typeof AuthDashboardExpensiveRouteImport
      parentRoute: typeof AuthDashboardRouteRoute
    }
    '/_auth/dashboard/messages': {
      id: '/_auth/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof AuthDashboardMessagesRouteRouteImport
      parentRoute: typeof AuthDashboardRouteRoute
    }
    '/_auth/dashboard/invoices': {
      id: '/_auth/dashboard/invoices'
      path: '/invoices'
      fullPath: '/dashboard/invoices'
      preLoaderRoute: typeof AuthDashboardInvoicesRouteRouteImport
      parentRoute: typeof AuthDashboardRouteRoute
    }
    '/_auth/dashboard/messages/': {
      id: '/_auth/dashboard/messages/'
      path: '/'
      fullPath: '/dashboard/messages/'
      preLoaderRoute: typeof AuthDashboardMessagesIndexRouteImport
      parentRoute: typeof AuthDashboardMessagesRouteRoute
    }
    '/_auth/dashboard/invoices/': {
      id: '/_auth/dashboard/invoices/'
      path: '/'
      fullPath: '/dashboard/invoices/'
      preLoaderRoute: typeof AuthDashboardInvoicesIndexRouteImport
      parentRoute: typeof AuthDashboardInvoicesRouteRoute
    }
    '/_auth/dashboard/invoices/$invoiceId': {
      id: '/_auth/dashboard/invoices/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/dashboard/invoices/$invoiceId'
      preLoaderRoute: typeof AuthDashboardInvoicesInvoiceIdRouteImport
      parentRoute: typeof AuthDashboardInvoicesRouteRoute
    }
  }
}

interface AuthDashboardInvoicesRouteRouteChildren {
  AuthDashboardInvoicesInvoiceIdRoute: typeof AuthDashboardInvoicesInvoiceIdRoute
  AuthDashboardInvoicesIndexRoute: typeof AuthDashboardInvoicesIndexRoute
}

const AuthDashboardInvoicesRouteRouteChildren: AuthDashboardInvoicesRouteRouteChildren =
  {
    AuthDashboardInvoicesInvoiceIdRoute: AuthDashboardInvoicesInvoiceIdRoute,
    AuthDashboardInvoicesIndexRoute: AuthDashboardInvoicesIndexRoute,
  }

const AuthDashboardInvoicesRouteRouteWithChildren =
  AuthDashboardInvoicesRouteRoute._addFileChildren(
    AuthDashboardInvoicesRouteRouteChildren,
  )

interface AuthDashboardMessagesRouteRouteChildren {
  AuthDashboardMessagesIndexRoute: typeof AuthDashboardMessagesIndexRoute
}

const AuthDashboardMessagesRouteRouteChildren: AuthDashboardMessagesRouteRouteChildren =
  {
    AuthDashboardMessagesIndexRoute: AuthDashboardMessagesIndexRoute,
  }

const AuthDashboardMessagesRouteRouteWithChildren =
  AuthDashboardMessagesRouteRoute._addFileChildren(
    AuthDashboardMessagesRouteRouteChildren,
  )

interface AuthDashboardRouteRouteChildren {
  AuthDashboardInvoicesRouteRoute: typeof AuthDashboardInvoicesRouteRouteWithChildren
  AuthDashboardMessagesRouteRoute: typeof AuthDashboardMessagesRouteRouteWithChildren
  AuthDashboardExpensiveRoute: typeof AuthDashboardExpensiveRoute
  AuthDashboardSettingsRoute: typeof AuthDashboardSettingsRoute
  AuthDashboardIndexRoute: typeof AuthDashboardIndexRoute
}

const AuthDashboardRouteRouteChildren: AuthDashboardRouteRouteChildren = {
  AuthDashboardInvoicesRouteRoute: AuthDashboardInvoicesRouteRouteWithChildren,
  AuthDashboardMessagesRouteRoute: AuthDashboardMessagesRouteRouteWithChildren,
  AuthDashboardExpensiveRoute: AuthDashboardExpensiveRoute,
  AuthDashboardSettingsRoute: AuthDashboardSettingsRoute,
  AuthDashboardIndexRoute: AuthDashboardIndexRoute,
}

const AuthDashboardRouteRouteWithChildren =
  AuthDashboardRouteRoute._addFileChildren(AuthDashboardRouteRouteChildren)

interface AuthRouteChildren {
  AuthDashboardRouteRoute: typeof AuthDashboardRouteRouteWithChildren
  AuthMyAccountRoute: typeof AuthMyAccountRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRouteRoute: AuthDashboardRouteRouteWithChildren,
  AuthMyAccountRoute: AuthMyAccountRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  PropertiesCreateRoute: PropertiesCreateRoute,
  PropertyPropertyIdRoute: PropertyPropertyIdRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
